name: CI
on: [push, pull_request]
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run CI script
      run: .github/workflows/ci.sh 
  test-bsd:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '13.2'
            host: ubuntu-latest
          - name: netbsd
            architecture: x86-64
            version: '9.3'
            host: ubuntu-latest
          - name: openbsd
            architecture: x86-64
            version: '7.4'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI script on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.22.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            .github/workflows/ci.sh
