name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y graphicsmagick
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: make test
